service: lambda2pushover
frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
   - serverless-dotenv-plugin

provider:
  name: aws
  region: ${env:AWS_REGION, self:custom.defaultRegion}
  defaultBucketName: ${self:service}-caption-bucket
  runtime: nodejs8.10
  environment:
    PUSHOVER_USER: ${env:PUSHOVER_USER}
    PUSHOVER_TOKEN: ${env:PUSHOVER_TOKEN}

custom:
  defaultRegion: 'ap-northeast-1'
  stage: ${opt:stage, self:provider.stage}

functions:
    main:
      handler: index.handler
      memorySize: 128
      timeout: 10
      events:
        - sns: snstopic-${self:service}-${self:custom.stage}

resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties: 
        DisplayName: snstopic-${self:service}-${self:custom.stage}
